name: stx_bloc_base
description: The package provides various generic implementations of blocs.
version: 0.5.0

homepage: https://github.com/VolodymyrSydorko/stx_bloc_base
documentation: https://github.com/VolodymyrSydorko/stx_bloc_base
repository: https://github.com/VolodymyrSydorko/stx_bloc_base

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  meta: ^1.9.1
  bloc_test: ^9.1.4

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.7
  lints: ^2.1.1
