name: stx_bloc_base
description: The package provides various generic implementations of blocs.
version: 0.5.1

homepage: https://github.com/VolodymyrSydorko/stx_bloc_base
documentation: https://github.com/VolodymyrSydorko/stx_bloc_base
repository: https://github.com/VolodymyrSydorko/stx_bloc_base

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.3
  equatable: ^2.0.5
  meta: ^1.10.0
  bloc_test: ^9.1.5

dev_dependencies:
  mocktail: ^1.0.2
  test: ^1.25.0
  lints: ^3.0.0
