name: stx_bloc_base
description: The package provides various generic implementations of blocs.
version: 0.6.0

homepage: https://github.com/VolodymyrSydorko/stx_bloc_base
documentation: https://github.com/VolodymyrSydorko/stx_bloc_base
repository: https://github.com/VolodymyrSydorko/stx_bloc_base

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  meta: ^1.15.0


dev_dependencies:
  test: ^1.25.14
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  lints: ^5.1.1
