name: stx_bloc_base
description: The package provides various generic implementations of blocs.
version: 0.4.5

homepage: https://github.com/VolodymyrSydorko/stx_bloc_base
documentation: https://github.com/VolodymyrSydorko/stx_bloc_base
repository: https://github.com/VolodymyrSydorko/stx_bloc_base

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5
  meta: ^1.8.0
  bloc_test: ^9.1.0
  tuple: ^2.0.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.1
  lints: ^2.0.1
