name: stx_bloc_base
description: The package provides various generic implementations of blocs.
version: 0.1.3

homepage: https://github.com/VolodymyrSydorko/stx_bloc_base
documentation: https://github.com/VolodymyrSydorko/stx_bloc_base
repository: https://github.com/VolodymyrSydorko/stx_bloc_base

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.6  
  lints: ^2.0.0
